--- #YAML:1.0
name:                Swishetest
version:             0.04a
abstract:            Library routines for the Swishetest tool
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Josh Rabinowitz <joshr@nonet>
